FROM ubuntu AS runtime

WORKDIR /transcoder
RUN  --mount=type=cache,target=/var/cache/apt 
RUN apt-get update -y && apt-get install -y 

RUN curl -sL https://deb.nodesource.com/setup_20.x | bash - && \
		apt-get install -y nodejs npm 
RUN apt-get install make git curl -y build-essential

RUN git clone https://github.com/ggerganov/whisper.cpp.git .
RUN ./download-ggml-model.sh base
RUN make -j
RUN ls -la 

COPY package*.json ./
COPY yarn.lock ./
RUN npm i yarn -g
RUN yarn
COPY . .
CMD [ "yarn" , "dev"]

