version: '3.8'

services:
    localstack:
        container_name: '${LOCALSTACK_DOCKER_NAME:-localstack-main}'
        image: localstack/localstack
        ports:
            - '127.0.0.1:4566:4566' # LocalStack Gateway
            - '127.0.0.1:4510-4559:4510-4559' # external services port range
        environment:
            # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
            - DEBUG=${DEBUG:-0}
        volumes:
            - '${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack'
            - '/var/run/docker.sock:/var/run/docker.sock'
    zookeeper:
        image: zookeeper
        container_name: zookeeper
        hostname: zookeeper
        ports:
            - 2181:2181
    kafka:
        image: confluentinc/cp-kafka
        container_name: kafka
        hostname: kafka
        environment:
            KAFKA_ZOOKEEPER_CONNECT: 192.168.1.13:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.13:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        ports:
            - 9092:9092
        depends_on:
            - zookeeper
